version: '3.7'
services:
  squash-tm-pg:
    container_name: squash-tm-pg
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    image: postgres:17
    volumes:
      - squash-tm-db-pg:/var/lib/postgresql/data
    networks:
      - db-network

  squash-tm:
    depends_on:
      - squash-tm-pg
    environment:
      SQTM_DB_TYPE: postgresql
      SQTM_DB_HOST: squash-tm-pg
      SQTM_DB_PORT: "5432"
      SQTM_DB_USERNAME: ${DB_USER}
      SQTM_DB_PASSWORD: ${DB_PASSWORD}
      SQTM_DB_NAME: ${DB_DATABASE}
    ports:
      - 8090:8080/tcp
    image: squashtest/squash
    volumes:
      - squash-tm-logs:/opt/squash-tm/logs
    networks:
      - db-network

volumes:
  squash-tm-logs:
  squash-tm-db-pg:

networks:
  db-network:
